spring:
  application:
    name: inditex
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    data: data.sql
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true



